version: '3.8'

services:
    server:
        build: ./server
        entrypoint: npm run dev
        ports:
            - 8080:8080
        environment: 
            - ACCESS_SECRET=<your_secret_here>
            - ACCESS_EXPIRE=60000 # 1 min
            - REFRESH_SECRET=<your_secret_here>
            - REFRESH_EXPIRE=600000 # 10 min
            - PORT=8080

        volumes: 
            - ./server:/server
